### ISSUE TITLE
[APP-0016] Create add exercise form in exercise pool

### ISSUE THREAD

**Issue by Bourbxn** [Project-IPCA/ipca-super-frontend#24]
### Guidelines
![Image](https://github.com/user-attachments/assets/45d28caf-ec87-4c1b-8978-b53925aac815)

### Task
- [x] Create add exercise form
- [x] Connect API for `Update` button
- [x] Connect API for `Reset` button
