### ISSUE TITLE
[APP-0017] Create summary card in student detail page

### ISSUE THREAD

**Issue by Bourbxn** [Project-IPCA/ipca-super-frontend#25]
### Guidelines
![Image](https://github.com/user-attachments/assets/2b48a6b8-6598-48e1-b5dd-da84c9550cc1)

### Task
- [x] Create summary card
- [x] Create breadcrumbs
- [x] Reset password button handler
- [x] Delete student button handler
- [x] Set permission student handler
