### ISSUE TITLE
[APP-0019] Create exercise detail for student

### ISSUE THREAD

**Issue by Bourbxn** [Project-IPCA/ipca-super-frontend#27]
### Guidelines
![Image](https://github.com/user-attachments/assets/17de3d66-99b6-4ea1-ae96-5d03be0aabc7)

### Task
- [x] Select display `page` or `modal`
- [x] Create exercise detail card
- [x] Create submission history card
