### ISSUE TITLE
[APP-0031] Add contraints part in add exercise modal in exercise pool page

### ISSUE THREAD

**Issue by Bourbxn** [Project-IPCA/ipca-super-frontend#61]
### Description
**PAGE** `Exercise Pool`
**FILE** `src/features/exerciseForm/ExerciseForm.tsx`
**NOTE**:
This component use for create and update exercise, So create and update to API should work

<img width="1211" alt="Image" src="https://github.com/user-attachments/assets/ef49f756-4f9c-44e3-a5f9-88951d2c4d3b" />

### Tasks
- [x] Add constraints manipulation
- [x] Add constraints to request API
- [x] Double check its work on update and create
